# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('demand', models.IntegerField(default=1)),
                ('ready_time', models.FloatField(default=0.0)),
                ('due_date', models.FloatField(default=0.0)),
                ('service_duration', models.FloatField(default=0.0)),
                ('position', geoposition.fields.GeopositionField(max_length=42, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nvehicles', models.IntegerField(default=1)),
                ('capacity', models.IntegerField(default=10)),
                ('ncustomers', models.IntegerField(default=0)),
                ('customers', models.ManyToManyField(to='problems.Customer')),
            ],
        ),
    ]
