# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_problem_ncustomers'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depot', to='problems.Customer'),
        ),
    ]
