# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20170115_1919'),
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['problem']},
        ),
        migrations.AlterModelOptions(
            name='routesequence',
            options={'ordering': ('route', 'position')},
        ),
        migrations.RenameField(
            model_name='route',
            old_name='route',
            new_name='customers',
        ),
        migrations.AddField(
            model_name='route',
            name='problem',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='problems.Problem'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='routesequence',
            unique_together=set([('route', 'position')]),
        ),
    ]
