# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 02:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_auto_20170115_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
