# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0004_auto_20170115_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='solution',
            name='solution_date',
        ),
        migrations.AddField(
            model_name='solution',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
