# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_auto_20170117_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routesequence',
            options={'ordering': ('route',)},
        ),
    ]
