# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0006_auto_20170117_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['username', 'created']},
        ),
        migrations.AddField(
            model_name='solution',
            name='cost',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='eq_iter',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='max_temp',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='min_temp',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='temp_change',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='username',
            field=models.CharField(default='anonymous', max_length=50),
            preserve_default=False,
        ),
    ]
