# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0007_auto_20170122_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='max_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='eq_iter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='max_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='min_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='temp_change',
            field=models.FloatField(default=0.0),
        ),
    ]
