# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20170115_1919'),
        ('solutions', '0008_auto_20170122_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('intra2opt', models.FloatField(default=0.0)),
                ('inter2opt', models.FloatField(default=0.0)),
                ('intraShift', models.FloatField(default=0.0)),
                ('interShift', models.FloatField(default=0.0)),
                ('cost', models.FloatField(default=0.0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem')),
            ],
            options={
                'ordering': ['cost'],
            },
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='solution',
            name='username',
        ),
    ]
